# docker-compose -f deploy/docker-compose/docker-compose.yaml up
version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql_server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DDWATCH
      MYSQL_USER: ROOT
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql.config:/path/to/mysql.config
      - mysql.log:/path/to/mysql.log
      - mysql.data:/path/to/mysql.data